deadline: "2019-09-28 22:00" #YYYY-MM-DD HH:MM in 24 hour format
zip_file_name: "AS1.zip" #make sure you have access to the directory of the zip file
grade_book_csv_input_file_name: "CPSC 231 (Fall 2024).csv" #grade book file name
grade_book_analysis: False #Default is False, set to True if you want to analyze the grade book
personal_days_column_id: 5 #column id for tracking the personal days
late_window: 15  #late duration window in minutes for the deadline
course_name: "CourseName"
assignment_name: "AssignmentName"
filter_label: "Late" #choose beetwen "LATE", "EARLY", and "LATE (within offset)"
early_label_on: True #choose beetwen "True" and "False" to show how early students submitted
output_format: "csv" #choose beetwen "excel" and "csv"